/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author resahh
 */
public class WorkerDataForm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WorkerDataForm.class.getName());

    /**
     * Creates new form WorkerDataForm
     */
    public WorkerDataForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        northPnl = new javax.swing.JPanel();
        modeLbl = new javax.swing.JLabel();
        eastPnl = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        southPnl = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        westPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        centerPnl = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nameTf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        hireTf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        roleTf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        depthTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        mainPnl.setLayout(new java.awt.BorderLayout());

        northPnl.setPreferredSize(new java.awt.Dimension(600, 40));
        northPnl.add(modeLbl);

        mainPnl.add(northPnl, java.awt.BorderLayout.PAGE_START);

        eastPnl.setPreferredSize(new java.awt.Dimension(150, 260));
        eastPnl.setLayout(new java.awt.GridLayout(4, 1));
        eastPnl.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        saveBtn.setText("Mentés");
        saveBtn.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanel10.add(saveBtn);

        eastPnl.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        cancelBtn.setText("Mégsem");
        cancelBtn.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanel11.add(cancelBtn);

        eastPnl.add(jPanel11);
        eastPnl.add(jPanel12);

        mainPnl.add(eastPnl, java.awt.BorderLayout.EAST);

        southPnl.setPreferredSize(new java.awt.Dimension(600, 40));
        southPnl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        exitBtn.setText("Kilépés");
        exitBtn.setPreferredSize(new java.awt.Dimension(110, 23));
        southPnl.add(exitBtn);

        mainPnl.add(southPnl, java.awt.BorderLayout.SOUTH);

        westPnl.setPreferredSize(new java.awt.Dimension(100, 220));
        westPnl.setLayout(new javax.swing.BoxLayout(westPnl, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setText("Név:");
        jPanel1.add(jLabel1);

        westPnl.add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("Belépés:");
        jPanel2.add(jLabel2);

        westPnl.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setText("Beosztás:");
        jPanel3.add(jLabel3);

        westPnl.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel4.setText("Részleg:");
        jPanel4.add(jLabel4);

        westPnl.add(jPanel4);

        mainPnl.add(westPnl, java.awt.BorderLayout.WEST);

        centerPnl.setLayout(new javax.swing.BoxLayout(centerPnl, javax.swing.BoxLayout.Y_AXIS));

        nameTf.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel5.add(nameTf);

        centerPnl.add(jPanel5);

        hireTf.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel6.add(hireTf);

        centerPnl.add(jPanel6);

        roleTf.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel7.add(roleTf);

        centerPnl.add(jPanel7);

        depthTf.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel8.add(depthTf);

        centerPnl.add(jPanel8);

        mainPnl.add(centerPnl, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPnl);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                WorkerDataForm dialog = new WorkerDataForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel centerPnl;
    private javax.swing.JTextField depthTf;
    private javax.swing.JPanel eastPnl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField hireTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JLabel modeLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JPanel northPnl;
    private javax.swing.JTextField roleTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel southPnl;
    private javax.swing.JPanel westPnl;
    // End of variables declaration//GEN-END:variables

    public JButton getSaveBtn(){ return saveBtn; }
    public JButton getCancelBtn(){ return cancelBtn; }
    public JButton getExitBtn(){ return exitBtn; }
    public JTextField getNameTf(){ return nameTf; }
    public void setNameTf( String text ){ nameTf.setText( text ); }
    public JTextField getHireTf(){ return hireTf; }
    public void setHireTf( String text ){ hireTf.setText( text ); }
    public JTextField getRoleTf(){ return roleTf; }
    public void setRoleTf( String text ){ roleTf.setText( text ); }
    public JTextField getDepthTf(){ return depthTf; }
    public void setDepthTf( String text ){ depthTf.setText( text ); }
    public void setModeLbl( String text ){ modeLbl.setText( text ); }
}
